# Generated by Django 5.0.4 on 2024-05-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MissionStatement',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
